import argparse
import json
import os

INPUT_FILE = "data/analysis_results.json"
OUTPUT_DIR = "docs"
THEMES_DIR = os.path.join(OUTPUT_DIR, "themes")
DEFAULT_MAX_ITEMS_PER_THEME = 50

TRAIT_COLORS = {
    "Cult of Tradition": "#ffcccc",
    "Rejection of Modernism": "#ffe5cc",
    "Action for Action's Sake": "#ffffcc",
    "Disagreement is Treason": "#e5ffcc",
    "Fear of Difference": "#ccffcc",
    "Appeal to Social Frustration": "#ccffe5",
    "Obsession with a Plot": "#ccffff",
    "Enemy is Strong and Weak": "#cce5ff",
    "Pacifism is Trafficking with the Enemy": "#ccccff",
    "Contempt for the Weak": "#e5ccff",
    "Everybody is Educated to Become a Hero": "#ffccff",
    "Machismo and Weaponry": "#ffcce5",
    "Selective Populism": "#e0e0e0",
    "Ur-Fascism Speaks Newspeak": "#ff9999"
}

def load_data():
    if not os.path.exists(INPUT_FILE):
        return []
    with open(INPUT_FILE, "r") as f:
        return json.load(f)

def slugify(text):
    return text.lower().replace(" ", "-").replace("'", "")


def parse_args():
    parser = argparse.ArgumentParser(description="Generate static theme pages for docs/")
    parser.add_argument(
        "--max-items-per-theme",
        type=int,
        default=DEFAULT_MAX_ITEMS_PER_THEME,
        help="Max quote cards per theme page (0 means no cap)",
    )
    return parser.parse_args()

def generate_header(title, depth=0):
    root = "../" * depth
    nav = f"""
    <nav style="background: #333; color: #fff; padding: 1rem; text-align: center;">
        <a href="{root}index.html" style="color: #fff; margin: 0 1rem; text-decoration: none;">Home</a>
        <a href="{root}themes_explained.html" style="color: #fff; margin: 0 1rem; text-decoration: none;">Themes & Sources</a>
        <a href="{root}graph/index.html" style="color: #fff; margin: 0 1rem; text-decoration: none;">Interactive Graph</a>
        <a href="{root}entities/index.html" style="color: #fff; margin: 0 1rem; text-decoration: none;">Entity Index</a>
        <a href="{root}ode.html" style="color: #fff; margin: 0 1rem; text-decoration: none;">The Ode</a>
    </nav>
    """
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{title}</title>
        <style>
            body {{ font-family: sans-serif; max-width: 900px; margin: 0 auto; line-height: 1.6; color: #333; }}
            a {{ color: #0066cc; text-decoration: none; }}
            a:hover {{ text-decoration: underline; }}
            .quote-card {{ background: #f9f9f9; border-left: 4px solid #ccc; padding: 1rem; margin-bottom: 1rem; }}
            .trait-tag {{ font-weight: bold; font-size: 0.9em; }}
            .theme-section {{ margin-bottom: 2rem; border-bottom: 1px solid #eee; padding-bottom: 1rem; }}
        </style>
    </head>
    <body>
        {nav}
        <div style="padding: 2rem;">
            <h1>{title}</h1>
    """

def generate_footer():
    return """
        </div>
        <footer style="text-align: center; padding: 2rem; border-top: 1px solid #eee; font-size: 0.8em; color: #666;">
            Generated by LangChain + Gemini-3-Flash. <br>
            <a href="https://github.com/langchain-ai/langchain">Powered by LangChain</a>
        </footer>
    </body>
    </html>
    """

def generate_about_themes():
    html = generate_header("Themes & Sources: Umberto Eco's Ur-Fascism")
    
    definitions = [
        ("1. Cult of Tradition", "Truth is already known; we must only interpret the obscure messages of the past."),
        ("2. Rejection of Modernism", "The Enlightenment, the Age of Reason is seen as the beginning of modern depravity."),
        ("3. Action for Action's Sake", "Thinking is a form of emasculation. Culture is suspect insofar as it is identified with critical attitudes."),
        ("4. Disagreement is Treason", "The critical spirit makes distinctions, and to distinguish is a sign of modernism."),
        ("5. Fear of Difference", "The first appeal of a fascist or prematurely fascist movement is an appeal against the intruders."),
        ("6. Appeal to Social Frustration", "Appeal to a frustrated middle class, suffering from an economic crisis or feelings of political humiliation."),
        ("7. Obsession with a Plot", "The followers must feel besieged. The easiest way to solve the plot is the appeal to xenophobia."),
        ("8. Enemy is Strong and Weak", "By a continuous shifting of rhetorical focus, the enemies are at the same time too strong and too weak."),
        ("9. Pacifism is Trafficking with the Enemy", "Life is permanent warfare."),
        ("10. Contempt for the Weak", "Elitism is a typical aspect of any reactionary ideology."),
        ("11. Everybody is Educated to Become a Hero", "In Ur-Fascism, heroism is the norm."),
        ("12. Machismo and Weaponry", "This is the origin of 'machismo' (which implies both disdain for women and intolerance and condemnation of nonstandard sexual habits)."),
        ("13. Selective Populism", "The People is conceived as a quality, a monolithic entity expressing the Common Will."),
        ("14. Ur-Fascism Speaks Newspeak", "All the Nazi or Fascist schoolbooks made use of an impoverished vocabulary, and an elementary syntax.")
    ]
    
    html += """
    <div style="max-width: 800px; margin: 0 auto;">
        <p>This analysis is based on <strong>Umberto Eco's</strong> essay <em>"Ur-Fascism"</em> (1995), originally published in the New York Review of Books. Eco identifies 14 "typical" features of fascism that may not be organized into a coherent system but form a "fuzzy" family resemblance.</p>
        
        <p>The analyzer identifies text segments that align with these definitions:</p>
    """
    
    for title, desc in definitions:
        trait_key = title.split(". ")[1]
        color = TRAIT_COLORS.get(trait_key, "#ccc")
        slug = slugify(trait_key)
        
        html += f"""
        <div class="theme-section" style="border-left: 5px solid {color}; padding-left: 1rem;">
            <h3><a href="themes/{slug}.html" style="color: inherit;">{title}</a></h3>
            <p>{desc}</p>
        </div>
        """
        
    html += """
        <p><em>Source: Eco, Umberto. "Ur-Fascism." The New York Review of Books, June 22, 1995.</em></p>
    </div>
    """
    html += generate_footer()
    
    with open(os.path.join(OUTPUT_DIR, "themes_explained.html"), "w") as f:
        f.write(html)

def generate_theme_pages(data, max_items_per_theme):
    os.makedirs(THEMES_DIR, exist_ok=True)
    
    # Group by trait
    traits = {t: [] for t in TRAIT_COLORS.keys()}
    
    for chunk in data:
        for concept in chunk.get("concepts", []):
            t = concept["trait"]
            if t in traits:
                payload = concept.copy()
                payload["chunk_id"] = chunk["chunk_id"]
                traits[t].append(payload)

    # Generate index of themes
    themes_index = "<ul>"
    
    for trait, items in traits.items():
        slug = slugify(trait)
        filename = f"{slug}.html"
        filepath = os.path.join(THEMES_DIR, filename)
        
        themes_index += f'<li><a href="themes/{filename}">{trait}</a> ({len(items)})</li>'
        
        # content
        display_items = items if max_items_per_theme <= 0 else items[:max_items_per_theme]

        html = generate_header(f"Trait: {trait}", depth=1)
        html += f"<p>Found {len(items)} instances of this trait.</p>"
        if max_items_per_theme > 0 and len(items) > len(display_items):
            html += f"<p>Showing top {len(display_items)} instances on this static page.</p>"
        
        for item in display_items:
            color = TRAIT_COLORS.get(trait, "#ccc")
            html += f"""
            <div class="quote-card" style="border-left-color: {color}">
                <blockquote>"{item['quote']}"</blockquote>
                <p>{item['explanation']}</p>
                <small>Confidence: {item['confidence']} | <a href="../index.html#chunk-{item['chunk_id']}">Chunk {item['chunk_id']}</a></small>
            </div>
            """
            
        html += generate_footer()
        
        with open(filepath, "w") as f:
            f.write(html)
            
    themes_index += "</ul>"
    return themes_index

def generate_landing(themes_list, data):
    html = generate_header("Project 2025 Analysis")
    
    html += """
    <h2>Overview</h2>
    <p>This project uses <strong>LangChain</strong> and <strong>Gemini-3-Flash</strong> to analyze the text of Project 2025, mapping it against Umberto Eco's 14 properties of Ur-Fascism.</p>
    
    <div style="text-align: center; margin-bottom: 2rem;">
        <a href="themes_explained.html" style="display: inline-block; padding: 0.5rem 1rem; background: #eee; color: #333; border-radius: 4px; border: 1px solid #ccc; margin-right: 1rem;">Read about the 14 Themes (Eco)</a>
        <a href="https://www.project2025.observer/en" style="display: inline-block; padding: 0.5rem 1rem; background: #eee; color: #333; border-radius: 4px; border: 1px solid #ccc;">Read the Original Text (External)</a>
    </div>
    
    <div style="display: flex; gap: 2rem; margin: 2rem 0;">
        <div style="flex: 1; padding: 1.5rem; background: #eef; border-radius: 8px;">
            <h3>🔍 Explore by Theme</h3>
            """ + themes_list + """
        </div>
        <div style="flex: 1; padding: 1.5rem; border: 1px solid #ddd; border-radius: 8px;">
            <h3>🕸️ Interactive Graph</h3>
            <p>Visualize the connections between text segments and fascist traits.</p>
            <a href="graph/index.html" style="display: inline-block; padding: 0.8rem 1.5rem; background: #0066cc; color: #fff; border-radius: 4px; text-decoration: none; font-weight: bold;">Launch Graph View</a>
        </div>
        <div style="flex: 1; padding: 1.5rem; border: 1px solid #ddd; border-radius: 8px;">
            <h3>🏷️ Entity Index</h3>
            <p>Browse extracted people, agencies, organizations, policies, legal references, and locations.</p>
            <a href="entities/index.html" style="display: inline-block; padding: 0.8rem 1.5rem; background: #0066cc; color: #fff; border-radius: 4px; text-decoration: none; font-weight: bold;">Browse Entities</a>
        </div>
    </div>
    """
    
    html += generate_footer()
    with open(os.path.join(OUTPUT_DIR, "index.html"), "w") as f:
        f.write(html)

def main():
    args = parse_args()
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    print("Loading data...")
    data = load_data()
    if not data:
        print("No data found!")
        return

    print("Generating Theme Pages...")
    themes_list = generate_theme_pages(data, args.max_items_per_theme)
    
    print("Generating Themes Explanation...")
    generate_about_themes()

    
    print("Generating Landing Page...")
    generate_landing(themes_list, data)
    
    print(f"Site generated in {OUTPUT_DIR}/")

if __name__ == "__main__":
    main()
